---
title: "Finances"
author: "Ethan Welty"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3

---

```{r setup, include=FALSE}
source("functions.R")
source("passwords.R")
knitr::opts_chunk$set(
  fig.width = 12, fig.align = "center", out.width = "100%", echo = FALSE,
  warning = FALSE, message = FALSE)
options(knitr.table.format = "html", knitr.kable.NA = "0") 
ggplot2::theme_set(ggplot2::theme_minimal(base_size = 14))
```

## Orders

```{r load orders, include=FALSE}
token <- pma_login(pma_user, pma_pass)
orders <- pma_get_table_cache(
    table = 'custom_view_dw_archived_invoice_user_totals_bouldercoopfood',
    path = file.path('cache', 'orders.rds'),
    token = token
  ) %>%
  # Fix errors in data
  clean_foodclub_orders() %>%
  # Format data
  format_foodclub_orders() %>%
  # Remove member shares
  dplyr::filter(account_id != 'bcf_internal') %>%
  # Add foodclub = TRUE column
  tibble::add_column(foodclub = TRUE, .before = 1) %>%
  # Sort by date, then supplier, then user
  dplyr::arrange(order_date, account_id, user_id) %>%
  # Add markup
  dplyr::mutate(markup = collected - (price_paid + tax_paid + tax))
```

### Order date range

```{r print date range}
orders$order_date %>%
  range() %>%
  paste(collapse = " to ") %>%
  cat()
```

### Average monthly order (by user)

```{r table: average monthly order by user}
orders %>%
  dplyr::group_by(user_id) %>%
  dplyr::summarize(
    price = sum(price_paid),
    tax = sum(tax),
    markup = sum(markup),
    total = sum(collected),
    months = 0.51 + as.numeric(diff(range(order_date)), units = "days") / 30.44
  ) %>%
  dplyr::mutate_at(vars(-months, -user_id), funs(divide_by(., months))) %>%
  dplyr::mutate_if(is.numeric, round) %>%
  dplyr::arrange(-total) %>%
  knitr::kable(digits = 0, format.args = list(big.mark = ",")) %>%
  kableExtra::kable_styling(bootstrap_options = "striped", full_width = FALSE)
```

### Order size (by supplier)

```{r figure: order size by supplier}
orders %>%
  dplyr::group_by(account_id, order_date) %>%
  dplyr::summarize_if(is.numeric, sum) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(
    account_id = gsub("bcf_", "", account_id),
    account_id = reorder(account_id, -price_paid, FUN = median)
  ) %>%
  ggplot2::ggplot(ggplot2::aes(account_id, price_paid)) +
   ggplot2:: geom_boxplot() +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))
```

### Order size (by user)

```{r figure: order size by user}
orders %>%
  dplyr::group_by(user_id, order_date) %>%
  dplyr::summarize_if(is.numeric, sum) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(
    user_id = reorder(user_id, -price_paid, FUN = median)
  ) %>%
  ggplot2::ggplot(ggplot2::aes(user_id, price_paid)) +
    ggplot2::geom_boxplot() + 
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))
```

### Monthy order (by supplier)

```{r figure: monthly order by supplier}
totals <- orders %>%
    dplyr::mutate(month = as.Date(format(order_date, "%Y-%m-01"))) %>%
    dplyr::group_by(month) %>%
    dplyr::summarize_if(is.numeric, sum) %>%
    dplyr::mutate(account_id = "Total")
orders %>%
  dplyr::mutate(
    month = as.Date(format(order_date, "%Y-%m-01"))
  ) %>%
  dplyr::group_by(account_id, month) %>%
  dplyr::summarize_if(is.numeric, sum) %>%
  dplyr::bind_rows(totals) %>%
  ggplot2::ggplot(ggplot2::aes(month, price_paid, color = account_id)) +
    ggplot2::geom_line(alpha = 0.5) +
    ggplot2::geom_smooth(se = FALSE)
```

### Monthy order (by top users)

```{r figure: monthly order by user}
top_users <- orders %>%
  dplyr::group_by(user_id) %>%
  dplyr::summarize_if(is.numeric, sum) %>%
  dplyr::filter(collected >= sort(collected, decreasing = TRUE)[7]) %$%
  user_id
orders %>%
  dplyr::filter(user_id %in% top_users) %>%
  dplyr::mutate(
    month = as.Date(format(order_date, "%Y-%m-01"))
  ) %>%
  dplyr::group_by(user_id, month) %>%
  dplyr::summarize_if(is.numeric, sum) %>%
  ggplot2::ggplot(ggplot2::aes(month, price_paid, color = user_id)) +
    ggplot2::geom_line(alpha = 0.4) +
    ggplot2::geom_smooth(se = FALSE) +
    ggplot2::scale_y_continuous(
      limits = c(0, 1000), oob = function(x, lim) {return(x)})
```

## Products

```{r load products, include=FALSE}
pma_token <- pma_login(pma_user, pma_pass)
products <- pma_get_table_cache(
    table = 'custom_view_archived_orders_bouldercoopfood',
    path = file.path('cache', 'products.rds'),
    hex = c('user_id', 'code'), token = token
  ) %>%
  dplyr::filter(account_id != "bcf_internal")
# TODO: Seperate by account_id because some codes overlap (Equal Exchange, Frontier)
# HACK: Exclude Frontier for now
codes <- list(
  # Oils
  "Olive oil (organic)" = c("olol[0-9]+", "olive_oil"),
  "Canola oil (organic)" = c("olca[0-9]+"),
  "Sunflower oil (organic)" = c("olsu[0-9]+"),
  "Coconut oil (organic)" = c("olcv[0-9]+|olco[0-9]+"),
  "Balsamic vinegar" = c("balsamic_vinegar"),
  "White vinegar" = c("white_vinegar"),
  "Apple cider vinegar (organic)" = c("apple_vinegar"),
  # Dairy & Alternatives
  "Butter (organic)" = c("butter"),
  "Butter" = c("butter_irish", "butter_unsalted"),
  "Cheddar cheese" = c("cheddar", "xtrasharp_cheddar"),
  "Goat cheese" = c("goat_cheese"),
  "Coconut milk (organic)" = c("nv10cocm", "coconutmilk"),
  # Eggs
  "Eggs (organic)" = c("5eggs", "eggs"),
  # Sweeteners
  "Maple syrup (organic)" = c("mapl[0-9]+gal", "maple_syrup"),
  "Agave syrup (organic)" = c("agac[0-9]+", "agdk[0-9]+", "agcldrum"),
  "Honey (Colorado)" = c("hon[0-9]+", "hocl[0-9]+"),
  "Cane sugar (organic)" = c("suga[0-9]+", "supo[0-9]+", "cane_sugar"),
  "Chocolate chips (organic)" = c("18611", "18664", "18665", "choc[0-9]+", "chocl[0-9]+", "chocs[0-9]+"),
  # Nuts
  "Peanut butter (organic)" = c("pnbc[0-9]+", "peanut_butter"),
  "Peanuts (organic)" = c("pntr[0-9]+", "pntb[0-9]+"),
  # "Cashews (organic)" = c("casw[0-9]+", "casp[0-9]+", "caswl[0-9]+", "61211", "61217", "61214"),
  "Cashews: whole (organic)" = c("casw[0-9]+", "caswl[0-9]+", "61211", "61217", "61214"),
  "Cashews: pieces (organic)" = c("casp[0-9]+"),
  "Cashews: pieces" = c("cashews"),
  "Almonds" = c("almonds"),
  "Almonds (organic)" = c("almn[0-9]+", "alms[0-9]+", "organic_almonds", "60203", "60204", "60206", "60202"),
  "Walnuts (organic)" = c("waln[0-9]+", "walp[0-9]+"),
  "Pecans (organic)" = c("peca[0-9]+", "pecp[0-9]+"),
  "Pecans" = c("pecans"),
  "Sunflower seeds (organic)" = c("sprs[0-9]+", "sund[0-9]+", "sund[0-9]+", "sunh[0-9]+"),
  "Pumpkin seeds (organic)" = c("puAA[0-9\\.]+"),
  "Flax seeds (organic)" = c("brof[0-9]+", "golf[0-9]+", "563"),
  "Sesame seeds: hulled (organic)" = c("sesh25"),
  # Beans, Cereals, Rice
  "Black beans (organic)" = c("blb[0-9]+"),
  "Pinto beans (organic)" = c("pinb[0-9]+"),
  "Garbanzo beans (organic)" = c("garm[0-9]+", "gars[0-9]+"),
  "Kidney beans (organic)" = c("kidb[0-9]+"),
  "Red lentils (organic)" = c("rdld[0-9]+", "rdln[0-9]+"),
  "Green lentils (organic)" = c("frgl[0-9]+", "grel[0-9]+"),
  "Rice (organic)" = c("riwbn[0-9]+", "riar[0-9]+", "ribw[0-9]+", "risu[0-9]+", "riwj[0-9]+", "riwl[0-9]+", "masoori_rice", "risg[0-9]+", "rilgn[0-9]+", "risgn[0-9]+", "ribb[0-9]+", "ribm[0-9]+", "rijb[0-9]+", "rilb[0-9]+", "risw[0-9]+", "brown_rice"),
  # "White rice (organic)" = c("riwbn[0-9]+", "riar[0-9]+", "ribw[0-9]+", "risu[0-9]+", "riwj[0-9]+", "riwl[0-9]+", "masoori_rice"),
  # "Brown rice (organic)" = c("risg[0-9]+", "rilgn[0-9]+", "risgn[0-9]+", "ribb[0-9]+", "ribm[0-9]+", "rijb[0-9]+", "rilb[0-9]+", "risw[0-9]+", "brown_rice"),
  "Polenta (organic)" = c("pole[0-9]+"),
  "Popcorn (organic)" = c("popc[0-9]+", "popm[0-9]+", "popw[0-9]+"),
  "Rolled oats (organic)" = c("oati[0-9]+", "quik[0-9]+", "quro[0-9]+", "rego[0-9]+", "rero[0-9]+", "tcut[0-9]+", "thro[0-9]+"),
  "Steel cut oats (organic)" = c("stco[0-9]+"),
  "Quinoa (organic)" = c("quin[0-9]+", "quir[0-9]+", "quit[0-9]+", "quib[0-9]+"),
  "Buckwheat (organic)" = c("bucw[0-9]+"),
  # Flours
  "White wheat flour (organic)" = c("apf[0-9]+", "uapf[0-9]+"),
  "Whole wheat flour (organic)" = c("whlwf[0-9]+", "whwpfl[0-9]+"),
  "Spelt flour (organic)" = c("spfl[0-9]+", "spwh[0-9]+"),
  # Pasta, Tortilla
  "Couscous (organic)" = c("cous[0-9]+", "cousw[0-9]+", "pearl_couscous"),
  "Wheat pasta (organic)" = c("mixed_pasta"),
  "Flour tortillas (organic)" = c("tortillas_raw_org"),
  "Flour tortillas" = c("flour_tortillas_8", "flour_tortillas_10", "tortillas_raw_conv"),
  "Corn tortilla chips (organic)" = c("tortilla_chips"),
  # Fruit
  "Frozen blueberries (organic)" = c("blueberries_froz"),
  "Frozen strawberries (organic)" = c("strawberries_froz"),
  "Frozen mangos (organic)" = c("mangoes_froz"),
  "Dates (organic)" = c("dapt[0-9]+", "datm[0-9]+", "deglet_dates"),
  "Dried apples (organic)" = c("apdi[0-9]+", "apri[0-9]+"),
  "Dried apricots (organic)" = c("apr[0-9]+", "dried_apricots", "61255"),
  "Raisins (organic)" = c("raif[0-9]+", "rais[0-9]+", "raist[0-9]+", "raisu[0-9]+", "raig[0-9]+", "raim[0-9]+"),
  "Dried figs (organic)" = c("fibm[0-9]+", "fig[0-9]+", "figo[0-9]+", "dried_figs"),
  "Dried mangos (organic)" = c("mang[0-9]+", "dried_mangoes_organic", "61253"),
  "Lemon juice (organic)" = c("lemon_juice"),
  # Vegetables
  "Tomatoes, diced, canned (organic)" = c("nv10todi", "diced_tomatoes"),
  "Tomatoes, paste, canned (organic)" = c("nv10topa", "tomato_paste"),
  "Onions" = c("onion_yellow"),
  "Garlic" = c("garlic", "peeled_garlic"),
  # Miscellaneous
  "Vanilla extract (organic)" = c("vanx[0-9]+", "23182", "23183", "23184"),
  "Coffee (organic)" = c(
    "coffee", "espresso_mantecca", "10001", 
    products %>%
      dplyr::filter(account_id == "bcf_consciouscoffee", grepl("organic", description, ignore.case = TRUE)) %$%
      code,
    products %>%
      dplyr::filter(account_id == "bcf_equalexchange", grepl("Espresso|Roast", description, ignore.case = TRUE)) %$%
      code
  ),
  # Baking
  "Baking powder" = c("2313"),
  # Spices
  "Salt" = c("salrm[0-9]+", "sare[0-9]+", "saresh", "sarf[0-9]+"),
  "Nutritional yeast" = c("2326", "2328", "2388"),
  "Smoked paprika (organic)" = c("4873"),
  "Smoked paprika" = c("4426"),
  "Garlic powder (organic)" = c("352"),
  "Garlic poweder" = c("149"),
  "Garlic granules (organic)" = c("2524"),
  "Onion powder (organic)" = c("371"),
  "Oregano (organic)" = c("281"),
  "Oregano" = c("173", "175"),
  "Thyme (organic)" = c("378"),
  "Ceylon cinnamon: powder (organic, fair trade)" = c("7006"),
  "Lavender (organic)" = c("1310"),
  "Cumin seeds (organic)" = c("2591"),
  "Black peppercorns (organic)" = c("2603", "7003", "2955"),
  "Black peppercorns" = c("183", "248"),
  "Nutmeg: ground (organic)" = c("2607"),
  "Ginger root: powder (organic)" = c("7010", "2610"),
  "Ginger root: powder" = c("370"),
  # Teas
  "Earl grey black tea" = c("1006"),
  "Earl grey black tea (organic)" = c("2826"),
  "Jasmine green tea (organic)" = c("1011"),
  "Rooibos tea (organic, fair trade)" = c("2828"),
  "English breakfast tea (organic)" = c("1078"),
  "English breakfast tea" = c("1007"),
  # House & Body
  "Toilet paper (recycled)" = c("tp"),
  "Paper towels (recycled)" = c("paper_towels"),
  "Dish soap" = c("dish_soap"),
  "Laundry detergent" = c("laundry_detergent", "tide_powder")
) %>%
  sapply(function(x) {paste0("^", x, "$", collapse = "|")})
products$category <- NULL
for (i in seq_along(codes)) {
  index <- grepl(codes[[i]], products$code)
  products$category[index] <- names(codes)[i] 
}
```

### Order date range

```{r print date range}
products$order_date %>%
  range() %>%
  paste(collapse = " to ") %>%
  cat()
```

### Cost of product (by code)

```{r}
products %>%
  dplyr::group_by(account_id, code) %>%
  dplyr::summarise(
    description = dplyr::first(description),
    size = dplyr::first(size),
    count = sum(qty),
    price = round(sum(qty * price))
  ) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(
    percent = 100 * price / sum(price)
  ) %>%
  dplyr::arrange(-price) %>%
  knitr::kable(digits = 0, format.args = list(big.mark = ",")) %>%
  kableExtra::kable_styling(bootstrap_options = "striped", full_width = FALSE)
```

### Cost of product (by category)

```{r}
products %>%
  dplyr::filter(!is.na(category)) %>%
  dplyr::group_by(category) %>%
  dplyr::summarise(
    price = round(sum(qty * price)),
    # account_ids = paste(sort(unique(account_id)), collapse = ", "),
    codes = paste(sort(unique(code)), collapse = ", ")
  ) %>%
  dplyr::mutate(
    percent = 100 * price / sum(price)
  ) %>%
  dplyr::arrange(-price) %>%
  dplyr::select(
    category, price, percent, codes
  ) %>%
  knitr::kable(digits = 0, format.args = list(big.mark = ",")) %>%
  kableExtra::kable_styling(bootstrap_options = "striped", full_width = FALSE)
```

### Uncategorized products

```{r}
products %>%
  dplyr::filter(is.na(category)) %>%
  dplyr::group_by(account_id, code) %>%
  dplyr::summarise(
    description = description[1],
    count = sum(qty),
    price = round(sum(qty * price))
  ) %>%
  dplyr::arrange(-price) %>%
  knitr::kable(digits = 0, format.args = list(big.mark = ",")) %>%
  kableExtra::kable_styling(bootstrap_options = "striped", full_width = FALSE)
```